# Generated by Django 6.1.1 on 2026-09-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.ImageField(default='https://static.vecteezy.com/system/resources/thumbnails/020/398/609/small_2x/restaurant-building-with-flat-style-isolated-on-white-background-vector.jpg', max_length=200, upload_to='')),
                ('cuisine', models.CharField(max_length=200)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mail',
            new_name='email',
        ),
    ]
