# Generated by Django 6.1.1 on 2026-09-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant_rename_mail_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://www.google.com/imgres?q=restaurant&imgurl=https%3A%2F%2Fcdn-icons-png.flaticon.com%2F256%2F6643%2F6643359.png&imgrefurl=https%3A%2F%2Fwww.flaticon.com%2Ffree-icon%2Frestaurant_6643359&docid=i4nSkHbAcIheUM&tbnid=vuWhU6uerpsbsM&vet=12ahUKEwjdm5XZ8_WWAxW1RWwGHcwDDhYQnPAOegQIPBAA..i&w=256&h=256&hcb=2&ved=2ahUKEwjdm5XZ8_WWAxW1RWwGHcwDDhYQnPAOegQIPBAA'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('vegeterian', models.BooleanField(default=False)),
                ('picture', models.URLField(default='https://www.indiafilings.com/learn/wp-content/uploads/2024/08/How-to-Start-Food-Business.jpg', max_length=400)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.restaurant')),
            ],
        ),
    ]
