# Generated by Django 6.1.1 on 2026-09-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_restaurant_picture_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBSL6Pir5R9e8SSWW63OEETBsjW7lctBcaaSZfZtvOn7AbbI_CGNN8FSvy&s=10'),
        ),
    ]
